### ISSUE TITLE
UTF8Control not encoding the german characters properly 

### ISSUE THREAD

**Issue by mfathy** [aymanizz/ktor-i18n#13]
**Describe the bug**
I am using Ktor-i18n version 2.0.0 and I realized that there is an encoding issue when encoding German characters like `ä` or `ü`.
Those characters become >> `�`

**To Reproduce**
Please create a resource with German characters for example Messages_de.properties:
`unavailable = Nicht verfügbar`

**Expected behavior**
Characters should be encoded correctly.

**Comment by Sterta** [comment]
@mfathy working for me correctly (ktor-i18n:2.0.0)

**Comment by mfathy** [comment]
@Sterta what could be the issue then?

**Comment by aymanizz** [comment]
Hi @mfathy, apologies for the delay. Since it's working for Sterta, it's highly unlikely to be an issue within the library. Did you manage to try Sterta's solution?

**Comment by mfathy** [comment]
> @mfathy have you checked that your properties file is encoded in UTF-8 and not ISO-8859-1 or something else?

It could be that, I will check it and get back to you.

**Comment by mfathy** [comment]
Thanks, @Sterta & @aymanizz the file encoding was the issue.
