### ISSUE TITLE
The conversion from AcceptLanguage header to a Locale is not adequate

### ISSUE THREAD

**Issue by budius** [aymanizz/ktor-i18n#15]
**Describe the bug**
When supporting multiple locales based on the same language, the logic to find the best locale given a header is not adequate.

**To Reproduce**
Given: a server supportedLocales = `en-US, en-AU, en-IE, en-GB, and others`
When: a request with `en-GB` header is received
Then: `en-US` will be used.

**Expected behavior**
Expected: `en-GB` to be used

**Additional context**

I would need to do more tests, but it seems it's a simple case of switching in I18n.kt
from:
```
        val locale = Locale.filter(ranges, i18n.supportedLocales).firstOrNull()
            ?: Locale.lookup(ranges, i18n.supportedLocales)
            ?: i18n.defaultLocale
```
to:
```
        val locale = Locale.lookup(ranges, i18n.supportedLocales)
            ?: Locale.filter(ranges, i18n.supportedLocales).firstOrNull()
            ?: i18n.defaultLocale
```
it happens because `Locale.filter(...).firstOrNull()` will match the first locale and ignore that a more specific locale exists in the range, while the Java implementation for `lookup()` was created to find the best match.

**Comment by aymanizz** [comment]
Good catch, thanks for the solution suggestion. If you'd like you can open a PR with these changes along with a simple test if possible to verify it's working as intended and to avoid regressions in the future.

**Comment by budius** [comment]
Wrote some tests and tried to find the exact combination, but can't repro.
I was not aware before, but it seems that `Locale.filter` it's not just a filter, but also re-order based on priority defined on standard RFC 4647.
