### ISSUE TITLE
Use i18n with FreeMarker

### ISSUE THREAD

**Issue by NathanFallet** [aymanizz/ktor-i18n#16]
**Is your feature request related to a problem? Please describe.**
I've been looking for an optimized way to use i18n with FreeMarker, see bellow how and what I've used currently.

**Describe the solution you'd like**
I don't know if it's possible; I would love to be able to call `call.t` from FreeMarker, as a function, or with a custom tag.

**Describe alternatives you've considered**
Currently I'm passing translations as a map, but it's not optimized at all, as I need to have explicit declarations of the ones I need:
```kt
call.respond(FreeMarkerContent("test.ftl", mapOf(
    "t" to mapOf(
        "key" to call.t(R("key")),
        // ...
    ),
    // Other custom data ...
)))
```

**Additional context**
I saw there is a function feature in FreeMarker, but I'm unable to pass `call.t` as a function, it gave me an error (it's passed as a string with the hash of the object and I cannot call it).

**Comment by aymanizz** [comment]
Hi, thanks for filing this issue.

Unfortunately, I don't have any experience with FreeMaker, but it seems possible to [implement a directive in Kotlin](https://freemarker.apache.org/docs/pgui_datamodel_directive.html) and then use the directive within the template.

This is something outside the scope of this plugin, and you'd have to implement it in your code or as a separate plugin. As such, I'll close this issue for now but feel free to continue the discussion.

**Comment by NathanFallet** [comment]
Hello! Just wanted to say that I finally made [a plugin to wrap i18n in FreeMarker](https://github.com/NathanFallet/KtorFreemarkerI18n). Feel free to add a link at the end of the README for `Usage with FreeMarker` if other people are interested by this.

**Comment by aymanizz** [comment]
That's great! I've added a section about it in README.
